// type
import { CartItem, Customer, Order, Product, Seller } from "./models";

const products: Product[] = [{
    id: 1,
    name: 'G-Series G30',
    category: 'Chevrolet',
    image: 'assets/images/products/product-1.jpg',
    added_date: '06/26/2019',
    rating: 5,
    price: 992.98,
    quantity: 459,
    status: true
}, {
    id: 2,
    name: 'Outlook',
    category: 'Saturn',
    image: 'assets/images/products/product-2.jpg',
    added_date: '02/12/2019',
    rating: 2,
    price: 294.05,
    quantity: 131,
    status: false
}, {
    id: 3,
    name: 'GL-Class',
    category: 'Mercedes-Benz',
    image: 'assets/images/products/product-3.jpg',
    added_date: '03/19/2019',
    rating: 5,
    price: 463.28,
    quantity: 188,
    status: true
}, {
    id: 4,
    name: 'F150',
    category: 'Ford',
    image: 'assets/images/products/product-4.jpg',
    added_date: '01/24/2019',
    rating: 2,
    price: 667.11,
    quantity: 314,
    status: true
}, {
    id: 5,
    name: 'S60',
    category: 'Volvo',
    image: 'assets/images/products/product-5.jpg',
    added_date: '08/15/2019',
    rating: 2,
    price: 542.41,
    quantity: 164,
    status: false
}, {
    id: 6,
    name: '626',
    category: 'Mazda',
    image: 'assets/images/products/product-6.jpg',
    added_date: '05/03/2019',
    rating: 2,
    price: 289.99,
    quantity: 492,
    status: true
}, {
    id: 7,
    name: 'LS',
    category: 'Lexus',
    image: 'assets/images/products/product-1.jpg',
    added_date: '11/17/2018',
    rating: 3,
    price: 380.42,
    quantity: 144,
    status: false
}, {
    id: 8,
    name: 'Quattroporte',
    category: 'Maserati',
    image: 'assets/images/products/product-2.jpg',
    added_date: '12/04/2018',
    rating: 5,
    price: 619.82,
    quantity: 482,
    status: true
}, {
    id: 9,
    name: 'Firebird',
    category: 'Pontiac',
    image: 'assets/images/products/product-3.jpg',
    added_date: '10/19/2019',
    rating: 4,
    price: 209.63,
    quantity: 139,
    status: true
}, {
    id: 10,
    name: 'GS',
    category: 'Lexus',
    image: 'assets/images/products/product-4.jpg',
    added_date: '10/18/2019',
    rating: 4,
    price: 830.24,
    quantity: 430,
    status: true
}, {
    id: 11,
    name: 'Excel',
    category: 'Mitsubishi',
    image: 'assets/images/products/product-5.jpg',
    added_date: '01/24/2019',
    rating: 2,
    price: 290.06,
    quantity: 408,
    status: false
}, {
    id: 12,
    name: 'XL7',
    category: 'Suzuki',
    image: 'assets/images/products/product-6.jpg',
    added_date: '12/30/2018',
    rating: 4,
    price: 733.93,
    quantity: 415,
    status: true
}, {
    id: 13,
    name: 'Cabriolet',
    category: 'Volkswagen',
    image: 'assets/images/products/product-1.jpg',
    added_date: '12/13/2018',
    rating: 5,
    price: 592.86,
    quantity: 60,
    status: true
}, {
    id: 14,
    name: 'S-Class',
    category: 'Mercedes-Benz',
    image: 'assets/images/products/product-2.jpg',
    added_date: '05/06/2019',
    rating: 3,
    price: 601.41,
    quantity: 189,
    status: false
}, {
    id: 15,
    name: 'Tredia',
    category: 'Mitsubishi',
    image: 'assets/images/products/product-3.jpg',
    added_date: '07/22/2019',
    rating: 1,
    price: 883.51,
    quantity: 61,
    status: true
}, {
    id: 16,
    name: 'Escalade ESV',
    category: 'Cadillac',
    image: 'assets/images/products/product-4.jpg',
    added_date: '05/27/2019',
    rating: 4,
    price: 782.01,
    quantity: 123,
    status: false
}, {
    id: 17,
    name: 'Mariner',
    category: 'Mercury',
    image: 'assets/images/products/product-5.jpg',
    added_date: '02/27/2019',
    rating: 4,
    price: 765.89,
    quantity: 399,
    status: false
}, {
    id: 18,
    name: 'Outback',
    category: 'Subaru',
    image: 'assets/images/products/product-6.jpg',
    added_date: '11/16/2018',
    rating: 4,
    price: 759.7,
    quantity: 233,
    status: false
}, {
    id: 19,
    name: 'CX-9',
    category: 'Mazda',
    image: 'assets/images/products/product-1.jpg',
    added_date: '10/05/2019',
    rating: 4,
    price: 567.08,
    quantity: 236,
    status: true
}, {
    id: 20,
    name: 'Envoy',
    category: 'GMC',
    image: 'assets/images/products/product-2.jpg',
    added_date: '12/31/2018',
    rating: 1,
    price: 684.37,
    quantity: 262,
    status: true
}, {
    id: 21,
    name: '2500',
    category: 'Chevrolet',
    image: 'assets/images/products/product-3.jpg',
    added_date: '09/19/2019',
    rating: 3,
    price: 917.8,
    quantity: 399,
    status: true
}, {
    id: 22,
    name: '911',
    category: 'Porsche',
    image: 'assets/images/products/product-4.jpg',
    added_date: '03/31/2019',
    rating: 2,
    price: 626.21,
    quantity: 361,
    status: true
}, {
    id: 23,
    name: 'Caliber',
    category: 'Dodge',
    image: 'assets/images/products/product-5.jpg',
    added_date: '06/30/2019',
    rating: 2,
    price: 797.34,
    quantity: 41,
    status: false
}, {
    id: 24,
    name: 'Pajero',
    category: 'Mitsubishi',
    image: 'assets/images/products/product-6.jpg',
    added_date: '11/16/2018',
    rating: 5,
    price: 615.29,
    quantity: 95,
    status: true
}, {
    id: 25,
    name: 'M5',
    category: 'BMW',
    image: 'assets/images/products/product-1.jpg',
    added_date: '05/01/2019',
    rating: 5,
    price: 737.74,
    quantity: 251,
    status: true
}, {
    id: 26,
    name: 'Sienna',
    category: 'Toyota',
    image: 'assets/images/products/product-2.jpg',
    added_date: '05/31/2019',
    rating: 2,
    price: 416.04,
    quantity: 122,
    status: true
}, {
    id: 27,
    name: 'Grand Caravan',
    category: 'Dodge',
    image: 'assets/images/products/product-3.jpg',
    added_date: '02/09/2019',
    rating: 2,
    price: 866.99,
    quantity: 280,
    status: false
}, {
    id: 28,
    name: 'Taurus',
    category: 'Ford',
    image: 'assets/images/products/product-4.jpg',
    added_date: '04/18/2019',
    rating: 2,
    price: 551.53,
    quantity: 49,
    status: true
}, {
    id: 29,
    name: 'Econoline E150',
    category: 'Ford',
    image: 'assets/images/products/product-5.jpg',
    added_date: '03/17/2019',
    rating: 4,
    price: 197.76,
    quantity: 440,
    status: false
}, {
    id: 30,
    name: 'Mini Cooper',
    category: 'Austin',
    image: 'assets/images/products/product-6.jpg',
    added_date: '06/19/2019',
    rating: 3,
    price: 508.98,
    quantity: 221,
    status: false
}, {
    id: 31,
    name: 'B-Series',
    category: 'Mazda',
    image: 'assets/images/products/product-1.jpg',
    added_date: '03/11/2019',
    rating: 4,
    price: 463.47,
    quantity: 353,
    status: false
}, {
    id: 32,
    name: 'Interceptor',
    category: 'Jensen',
    image: 'assets/images/products/product-2.jpg',
    added_date: '02/19/2019',
    rating: 2,
    price: 753.96,
    quantity: 76,
    status: false
}, {
    id: 33,
    name: 'Grand Prix',
    category: 'Pontiac',
    image: 'assets/images/products/product-3.jpg',
    added_date: '05/18/2019',
    rating: 5,
    price: 326.9,
    quantity: 269,
    status: true
}, {
    id: 34,
    name: '300',
    category: 'Chrysler',
    image: 'assets/images/products/product-4.jpg',
    added_date: '11/26/2018',
    rating: 3,
    price: 554.84,
    quantity: 212,
    status: true
}, {
    id: 35,
    name: 'Ram Van 3500',
    category: 'Dodge',
    image: 'assets/images/products/product-5.jpg',
    added_date: '09/09/2019',
    rating: 2,
    price: 728.15,
    quantity: 223,
    status: true
}, {
    id: 36,
    name: 'Integra',
    category: 'Acura',
    image: 'assets/images/products/product-6.jpg',
    added_date: '09/25/2019',
    rating: 2,
    price: 791.85,
    quantity: 21,
    status: true
}, {
    id: 37,
    name: 'Grand Prix',
    category: 'Pontiac',
    image: 'assets/images/products/product-1.jpg',
    added_date: '11/07/2019',
    rating: 1,
    price: 109.51,
    quantity: 446,
    status: true
}, {
    id: 38,
    name: 'Boxster',
    category: 'Porsche',
    image: 'assets/images/products/product-2.jpg',
    added_date: '11/08/2019',
    rating: 3,
    price: 702.78,
    quantity: 445,
    status: false
}, {
    id: 39,
    name: 'E-Series',
    category: 'Ford',
    image: 'assets/images/products/product-3.jpg',
    added_date: '04/02/2019',
    rating: 5,
    price: 752.6,
    quantity: 294,
    status: true
}, {
    id: 40,
    name: 'Ram',
    category: 'Dodge',
    image: 'assets/images/products/product-4.jpg',
    added_date: '12/19/2018',
    rating: 1,
    price: 509.55,
    quantity: 142,
    status: false
}, {
    id: 41,
    name: 'Sorento',
    category: 'Kia',
    image: 'assets/images/products/product-5.jpg',
    added_date: '05/15/2019',
    rating: 5,
    price: 433.24,
    quantity: 90,
    status: true
}, {
    id: 42,
    name: 'Sedona',
    category: 'Kia',
    image: 'assets/images/products/product-6.jpg',
    added_date: '05/23/2019',
    rating: 4,
    price: 407.97,
    quantity: 51,
    status: false
}, {
    id: 43,
    name: 'RX Hybrid',
    category: 'Lexus',
    image: 'assets/images/products/product-1.jpg',
    added_date: '05/23/2019',
    rating: 3,
    price: 386.63,
    quantity: 222,
    status: false
}, {
    id: 44,
    name: 'Altima',
    category: 'Nissan',
    image: 'assets/images/products/product-2.jpg',
    added_date: '08/22/2019',
    rating: 1,
    price: 692.1,
    quantity: 272,
    status: true
}, {
    id: 45,
    name: 'Tundra',
    category: 'Toyota',
    image: 'assets/images/products/product-3.jpg',
    added_date: '11/23/2018',
    rating: 5,
    price: 603.89,
    quantity: 370,
    status: false
}, {
    id: 46,
    name: 'LTD Crown Victoria',
    category: 'Ford',
    image: 'assets/images/products/product-4.jpg',
    added_date: '12/30/2018',
    rating: 5,
    price: 834.79,
    quantity: 256,
    status: true
}, {
    id: 47,
    name: 'Classic',
    category: 'Chevrolet',
    image: 'assets/images/products/product-5.jpg',
    added_date: '02/05/2019',
    rating: 4,
    price: 341.37,
    quantity: 88,
    status: false
}, {
    id: 48,
    name: 'S10',
    category: 'Chevrolet',
    image: 'assets/images/products/product-6.jpg',
    added_date: '02/25/2019',
    rating: 5,
    price: 502.81,
    quantity: 8,
    status: false
}, {
    id: 49,
    name: 'Monte Carlo',
    category: 'Chevrolet',
    image: 'assets/images/products/product-1.jpg',
    added_date: '03/15/2019',
    rating: 3,
    price: 675.48,
    quantity: 253,
    status: true
}, {
    id: 50,
    name: 'Stealth',
    category: 'Dodge',
    image: 'assets/images/products/product-2.jpg',
    added_date: '06/04/2019',
    rating: 5,
    price: 667.05,
    quantity: 303,
    status: true
}, {
    id: 51,
    name: 'Grand Vitara',
    category: 'Suzuki',
    image: 'assets/images/products/product-3.jpg',
    added_date: '08/20/2019',
    rating: 4,
    price: 651.1,
    quantity: 307,
    status: true
}, {
    id: 52,
    name: 'H3',
    category: 'Hummer',
    image: 'assets/images/products/product-4.jpg',
    added_date: '09/21/2019',
    rating: 5,
    price: 955.26,
    quantity: 309,
    status: true
}, {
    id: 53,
    name: 'Santa Fe',
    category: 'Hyundai',
    image: 'assets/images/products/product-5.jpg',
    added_date: '06/04/2019',
    rating: 3,
    price: 728.71,
    quantity: 12,
    status: true
}, {
    id: 54,
    name: 'Miata MX-5',
    category: 'Mazda',
    image: 'assets/images/products/product-6.jpg',
    added_date: '04/15/2019',
    rating: 1,
    price: 844.04,
    quantity: 112,
    status: true
}, {
    id: 55,
    name: 'L-Series',
    category: 'Saturn',
    image: 'assets/images/products/product-1.jpg',
    added_date: '04/28/2019',
    rating: 2,
    price: 147.15,
    quantity: 313,
    status: true
}, {
    id: 56,
    name: 'Excel',
    category: 'Hyundai',
    image: 'assets/images/products/product-2.jpg',
    added_date: '07/20/2019',
    rating: 3,
    price: 593.89,
    quantity: 168,
    status: true
}, {
    id: 57,
    name: 'Tribute',
    category: 'Mazda',
    image: 'assets/images/products/product-3.jpg',
    added_date: '05/17/2019',
    rating: 4,
    price: 333.46,
    quantity: 13,
    status: false
}, {
    id: 58,
    name: 'Corvette',
    category: 'Chevrolet',
    image: 'assets/images/products/product-4.jpg',
    added_date: '04/20/2019',
    rating: 3,
    price: 193.54,
    quantity: 72,
    status: false
}, {
    id: 59,
    name: 'Azera',
    category: 'Hyundai',
    image: 'assets/images/products/product-5.jpg',
    added_date: '12/21/2018',
    rating: 2,
    price: 677.73,
    quantity: 462,
    status: false
}, {
    id: 60,
    name: 'Esprit',
    category: 'Lotus',
    image: 'assets/images/products/product-6.jpg',
    added_date: '08/11/2019',
    rating: 4,
    price: 883.49,
    quantity: 434,
    status: false
}, {
    id: 61,
    name: 'Trooper',
    category: 'Isuzu',
    image: 'assets/images/products/product-1.jpg',
    added_date: '06/30/2019',
    rating: 1,
    price: 199.83,
    quantity: 60,
    status: false
}, {
    id: 62,
    name: 'Tempo',
    category: 'Ford',
    image: 'assets/images/products/product-2.jpg',
    added_date: '09/08/2019',
    rating: 2,
    price: 872.85,
    quantity: 209,
    status: false
}, {
    id: 63,
    name: 'Space',
    category: 'Mitsubishi',
    image: 'assets/images/products/product-3.jpg',
    added_date: '06/15/2019',
    rating: 2,
    price: 250.64,
    quantity: 398,
    status: false
}, {
    id: 64,
    name: 'Sebring',
    category: 'Chrysler',
    image: 'assets/images/products/product-4.jpg',
    added_date: '07/31/2019',
    rating: 4,
    price: 782.48,
    quantity: 9,
    status: false
}, {
    id: 65,
    name: 'Fox',
    category: 'Volkswagen',
    image: 'assets/images/products/product-5.jpg',
    added_date: '04/04/2019',
    rating: 1,
    price: 431.8,
    quantity: 234,
    status: false
}, {
    id: 66,
    name: 'Mountaineer',
    category: 'Mercury',
    image: 'assets/images/products/product-6.jpg',
    added_date: '11/11/2018',
    rating: 1,
    price: 766.91,
    quantity: 228,
    status: false
}, {
    id: 67,
    name: 'Wrangler',
    category: 'Jeep',
    image: 'assets/images/products/product-1.jpg',
    added_date: '01/16/2019',
    rating: 5,
    price: 261.51,
    quantity: 222,
    status: false
}, {
    id: 68,
    name: 'Spectra5',
    category: 'Kia',
    image: 'assets/images/products/product-2.jpg',
    added_date: '04/08/2019',
    rating: 2,
    price: 677.71,
    quantity: 263,
    status: false
}, {
    id: 69,
    name: 'GTI',
    category: 'Volkswagen',
    image: 'assets/images/products/product-3.jpg',
    added_date: '01/20/2019',
    rating: 4,
    price: 472.59,
    quantity: 139,
    status: true
}, {
    id: 70,
    name: 'Cordia',
    category: 'Mitsubishi',
    image: 'assets/images/products/product-4.jpg',
    added_date: '03/14/2019',
    rating: 2,
    price: 628.21,
    quantity: 78,
    status: false
}, {
    id: 71,
    name: 'Pathfinder',
    category: 'Nissan',
    image: 'assets/images/products/product-5.jpg',
    added_date: '08/30/2019',
    rating: 1,
    price: 169.35,
    quantity: 232,
    status: true
}, {
    id: 72,
    name: 'Thunderbird',
    category: 'Ford',
    image: 'assets/images/products/product-6.jpg',
    added_date: '08/14/2019',
    rating: 3,
    price: 676.6,
    quantity: 319,
    status: false
}, {
    id: 73,
    name: '530',
    category: 'BMW',
    image: 'assets/images/products/product-1.jpg',
    added_date: '08/18/2019',
    rating: 1,
    price: 500.22,
    quantity: 172,
    status: true
}, {
    id: 74,
    name: 'Milan',
    category: 'Mercury',
    image: 'assets/images/products/product-2.jpg',
    added_date: '02/21/2019',
    rating: 1,
    price: 591.49,
    quantity: 485,
    status: true
}, {
    id: 75,
    name: 'Suburban 2500',
    category: 'Chevrolet',
    image: 'assets/images/products/product-3.jpg',
    added_date: '10/13/2019',
    rating: 2,
    price: 704.99,
    quantity: 10,
    status: false
}, {
    id: 76,
    name: 'Forte',
    category: 'Kia',
    image: 'assets/images/products/product-4.jpg',
    added_date: '10/23/2019',
    rating: 4,
    price: 901.01,
    quantity: 105,
    status: true
}, {
    id: 77,
    name: 'Riviera',
    category: 'Buick',
    image: 'assets/images/products/product-5.jpg',
    added_date: '03/23/2019',
    rating: 1,
    price: 837.11,
    quantity: 54,
    status: false
}, {
    id: 78,
    name: 'Reatta',
    category: 'Buick',
    image: 'assets/images/products/product-6.jpg',
    added_date: '07/06/2019',
    rating: 3,
    price: 704.59,
    quantity: 193,
    status: true
}, {
    id: 79,
    name: 'Caravan',
    category: 'Dodge',
    image: 'assets/images/products/product-1.jpg',
    added_date: '08/04/2019',
    rating: 3,
    price: 621.92,
    quantity: 495,
    status: true
}, {
    id: 80,
    name: 'Range Rover Classic',
    category: 'Land Rover',
    image: 'assets/images/products/product-2.jpg',
    added_date: '09/04/2019',
    rating: 3,
    price: 408.1,
    quantity: 126,
    status: true
}, {
    id: 81,
    name: 'Town Car',
    category: 'Lincoln',
    image: 'assets/images/products/product-3.jpg',
    added_date: '11/29/2018',
    rating: 1,
    price: 332.5,
    quantity: 300,
    status: true
}, {
    id: 82,
    name: 'XLR-V',
    category: 'Cadillac',
    image: 'assets/images/products/product-4.jpg',
    added_date: '07/31/2019',
    rating: 5,
    price: 969.44,
    quantity: 137,
    status: true
}, {
    id: 83,
    name: 'RX-7',
    category: 'Mazda',
    image: 'assets/images/products/product-5.jpg',
    added_date: '11/16/2018',
    rating: 3,
    price: 427.01,
    quantity: 193,
    status: false
}, {
    id: 84,
    name: 'E350',
    category: 'Ford',
    image: 'assets/images/products/product-6.jpg',
    added_date: '10/05/2019',
    rating: 1,
    price: 401.65,
    quantity: 474,
    status: false
}, {
    id: 85,
    name: 'Jetta',
    category: 'Volkswagen',
    image: 'assets/images/products/product-1.jpg',
    added_date: '01/24/2019',
    rating: 5,
    price: 250.91,
    quantity: 213,
    status: true
}, {
    id: 86,
    name: 'Fusion',
    category: 'Ford',
    image: 'assets/images/products/product-2.jpg',
    added_date: '07/26/2019',
    rating: 5,
    price: 584.36,
    quantity: 80,
    status: true
}, {
    id: 87,
    name: 'W201',
    category: 'Mercedes-Benz',
    image: 'assets/images/products/product-3.jpg',
    added_date: '08/04/2019',
    rating: 2,
    price: 281.65,
    quantity: 263,
    status: true
}, {
    id: 88,
    name: 'Blazer',
    category: 'Chevrolet',
    image: 'assets/images/products/product-4.jpg',
    added_date: '01/27/2019',
    rating: 3,
    price: 832.14,
    quantity: 58,
    status: true
}, {
    id: 89,
    name: 'Accord',
    category: 'Honda',
    image: 'assets/images/products/product-5.jpg',
    added_date: '03/04/2019',
    rating: 3,
    price: 303.54,
    quantity: 393,
    status: true
}, {
    id: 90,
    name: 'Biturbo',
    category: 'Maserati',
    image: 'assets/images/products/product-6.jpg',
    added_date: '03/11/2019',
    rating: 5,
    price: 211.38,
    quantity: 120,
    status: false
}, {
    id: 91,
    name: 'Dakota Club',
    category: 'Dodge',
    image: 'assets/images/products/product-1.jpg',
    added_date: '11/23/2018',
    rating: 4,
    price: 783.83,
    quantity: 461,
    status: false
}, {
    id: 92,
    name: 'Mustang',
    category: 'Ford',
    image: 'assets/images/products/product-2.jpg',
    added_date: '06/13/2019',
    rating: 5,
    price: 612.92,
    quantity: 382,
    status: true
}, {
    id: 93,
    name: 'Pilot',
    category: 'Honda',
    image: 'assets/images/products/product-3.jpg',
    added_date: '11/25/2018',
    rating: 5,
    price: 589.72,
    quantity: 246,
    status: false
}, {
    id: 94,
    name: 'S80',
    category: 'Volvo',
    image: 'assets/images/products/product-4.jpg',
    added_date: '02/01/2019',
    rating: 2,
    price: 596.59,
    quantity: 325,
    status: false
}, {
    id: 95,
    name: 'Grand Marquis',
    category: 'Mercury',
    image: 'assets/images/products/product-5.jpg',
    added_date: '01/28/2019',
    rating: 3,
    price: 102.64,
    quantity: 471,
    status: true
}, {
    id: 96,
    name: 'S-Class',
    category: 'Mercedes-Benz',
    image: 'assets/images/products/product-6.jpg',
    added_date: '11/21/2018',
    rating: 3,
    price: 553.84,
    quantity: 178,
    status: false
}, {
    id: 97,
    name: 'Freelander',
    category: 'Land Rover',
    image: 'assets/images/products/product-1.jpg',
    added_date: '09/13/2019',
    rating: 5,
    price: 682.82,
    quantity: 223,
    status: true
}, {
    id: 98,
    name: 'Crossfire',
    category: 'Chrysler',
    image: 'assets/images/products/product-2.jpg',
    added_date: '06/26/2019',
    rating: 2,
    price: 696.41,
    quantity: 411,
    status: true
}, {
    id: 99,
    name: 'Cabriolet',
    category: 'Volkswagen',
    image: 'assets/images/products/product-3.jpg',
    added_date: '01/11/2019',
    rating: 5,
    price: 667.44,
    quantity: 458,
    status: false
}, {
    id: 100,
    name: 'Mustang',
    category: 'Ford',
    image: 'assets/images/products/product-4.jpg',
    added_date: '02/02/2019',
    rating: 3,
    price: 350.01,
    quantity: 295,
    status: false
}];

const orders: Order[] = [
    {
        id: 1,
        order_id: '31',
        order_date: '23-May-2019',
        order_time: '1:45 PM',
        payment_status: 'Payment Failed',
        total: '$8361.93',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 2,
        order_id: '060',
        order_date: '01-Feb-2019',
        order_time: '12:10 PM',
        payment_status: 'Unpaid',
        total: '$6219.67',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 3,
        order_id: '76961',
        order_date: '13-Mar-2019',
        order_time: '2:53 AM',
        payment_status: 'Payment Failed',
        total: '$6695.83',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 4,
        order_id: '59',
        order_date: '02-Feb-2019',
        order_time: '2:53 AM',
        payment_status: 'Paid',
        total: '$8616.73',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 5,
        order_id: '93',
        order_date: '15-May-2019',
        order_time: '1:52 PM',
        payment_status: 'Awaiting Authorization',
        total: '$1808.61',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 6,
        order_id: '2164',
        order_date: '22-Feb-2019',
        order_time: '3:59 AM',
        payment_status: 'Paid',
        total: '$9813.57',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 7,
        order_id: '22410',
        order_date: '16-Jan-2019',
        order_time: '7:29 AM',
        payment_status: 'Awaiting Authorization',
        total: '$9457.23',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 8,
        order_id: '04260',
        order_date: '06-Feb-2019',
        order_time: '5:14 AM',
        payment_status: 'Unpaid',
        total: '$1054.76',
        payment_method: 'Payoneer',
        order_status: 'Processing',
    },
    {
        id: 9,
        order_id: '77',
        order_date: '18-Jan-2019',
        order_time: '9:34 AM',
        payment_status: 'Payment Failed',
        total: '$3526.87',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 10,
        order_id: '938',
        order_date: '27-Apr-2019',
        order_time: '6:16 PM',
        payment_status: 'Paid',
        total: '$8201.67',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 11,
        order_id: '99',
        order_date: '03-Mar-2019',
        order_time: '11:23 PM',
        payment_status: 'Payment Failed',
        total: '$9557.76',
        payment_method: 'Paypal',
        order_status: 'Processing',
    },
    {
        id: 12,
        order_id: '397',
        order_date: '12-May-2019',
        order_time: '11:18 PM',
        payment_status: 'Unpaid',
        total: '$8391.95',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 13,
        order_id: '4874',
        order_date: '01-Jan-2019',
        order_time: '2:15 PM',
        payment_status: 'Unpaid',
        total: '$3558.36',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 14,
        order_id: '496',
        order_date: '17-Apr-2019',
        order_time: '7:56 PM',
        payment_status: 'Payment Failed',
        total: '$2871.99',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 15,
        order_id: '982',
        order_date: '07-May-2019',
        order_time: '7:54 PM',
        payment_status: 'Awaiting Authorization',
        total: '$415.59',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 16,
        order_id: '66303',
        order_date: '14-Mar-2019',
        order_time: '10:47 AM',
        payment_status: 'Paid',
        total: '$9554.21',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 17,
        order_id: '73',
        order_date: '20-Feb-2019',
        order_time: '4:24 PM',
        payment_status: 'Payment Failed',
        total: '$9766.71',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 18,
        order_id: '90804',
        order_date: '03-Jun-2019',
        order_time: '5:42 PM',
        payment_status: 'Payment Failed',
        total: '$1194.25',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 19,
        order_id: '97489',
        order_date: '09-May-2019',
        order_time: '11:47 PM',
        payment_status: 'Paid',
        total: '$8715.09',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 20,
        order_id: '53577',
        order_date: '14-Jun-2019',
        order_time: '8:47 PM',
        payment_status: 'Unpaid',
        total: '$2836.42',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 21,
        order_id: '8940',
        order_date: '08-Jun-2019',
        order_time: '6:14 PM',
        payment_status: 'Paid',
        total: '$3552.93',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 22,
        order_id: '34334',
        order_date: '20-Apr-2019',
        order_time: '7:19 PM',
        payment_status: 'Payment Failed',
        total: '$7487.68',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 23,
        order_id: '2',
        order_date: '07-Jan-2019',
        order_time: '4:29 AM',
        payment_status: 'Paid',
        total: '$2900.64',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 24,
        order_id: '478',
        order_date: '19-Jun-2019',
        order_time: '9:29 AM',
        payment_status: 'Unpaid',
        total: '$7589.76',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 25,
        order_id: '95',
        order_date: '30-Mar-2019',
        order_time: '9:47 AM',
        payment_status: 'Unpaid',
        total: '$3774.83',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 26,
        order_id: '160',
        order_date: '05-Jun-2019',
        order_time: '1:39 PM',
        payment_status: 'Paid',
        total: '$2696.43',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 27,
        order_id: '81338',
        order_date: '19-Jun-2019',
        order_time: '4:59 PM',
        payment_status: 'Unpaid',
        total: '$4720.65',
        payment_method: 'Credit Card',
        order_status: 'Processing',
    },
    {
        id: 28,
        order_id: '75',
        order_date: '31-Jan-2019',
        order_time: '10:24 AM',
        payment_status: 'Unpaid',
        total: '$7674.74',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 29,
        order_id: '8',
        order_date: '16-Feb-2019',
        order_time: '5:08 AM',
        payment_status: 'Paid',
        total: '$2399.90',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 30,
        order_id: '99',
        order_date: '19-Jun-2019',
        order_time: '1:33 AM',
        payment_status: 'Payment Failed',
        total: '$2471.31',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 31,
        order_id: '976',
        order_date: '17-Jun-2019',
        order_time: '8:21 AM',
        payment_status: 'Unpaid',
        total: '$8073.28',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 32,
        order_id: '13',
        order_date: '17-Feb-2019',
        order_time: '5:41 AM',
        payment_status: 'Unpaid',
        total: '$4393.62',
        payment_method: 'Payoneer',
        order_status: 'Cancelled',
    },
    {
        id: 33,
        order_id: '8333',
        order_date: '14-Feb-2019',
        order_time: '4:42 AM',
        payment_status: 'Paid',
        total: '$6077.15',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 34,
        order_id: '21547',
        order_date: '22-Jul-2019',
        order_time: '8:42 PM',
        payment_status: 'Unpaid',
        total: '$5792.53',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 35,
        order_id: '25',
        order_date: '11-Jul-2019',
        order_time: '10:38 PM',
        payment_status: 'Payment Failed',
        total: '$8661.65',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
    {
        id: 36,
        order_id: '3201',
        order_date: '13-Jun-2019',
        order_time: '9:57 PM',
        payment_status: 'Payment Failed',
        total: '$7795.53',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 37,
        order_id: '797',
        order_date: '09-Mar-2019',
        order_time: '9:53 PM',
        payment_status: 'Paid',
        total: '$9755.20',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 38,
        order_id: '7078',
        order_date: '04-Jul-2019',
        order_time: '9:09 AM',
        payment_status: 'Unpaid',
        total: '$2335.70',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 39,
        order_id: '4380',
        order_date: '11-Apr-2019',
        order_time: '5:33 AM',
        payment_status: 'Awaiting Authorization',
        total: '$1342.74',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 40,
        order_id: '4',
        order_date: '23-May-2019',
        order_time: '11:35 AM',
        payment_status: 'Paid',
        total: '$626.28',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 41,
        order_id: '54',
        order_date: '11-Apr-2019',
        order_time: '1:51 AM',
        payment_status: 'Unpaid',
        total: '$1903.55',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 42,
        order_id: '6084',
        order_date: '01-Jan-2019',
        order_time: '11:08 AM',
        payment_status: 'Unpaid',
        total: '$1671.64',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 43,
        order_id: '7004',
        order_date: '12-Mar-2019',
        order_time: '6:18 AM',
        payment_status: 'Payment Failed',
        total: '$7471.41',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 44,
        order_id: '00890',
        order_date: '10-Jan-2019',
        order_time: '5:36 AM',
        payment_status: 'Payment Failed',
        total: '$7395.11',
        payment_method: 'Paypal',
        order_status: 'Processing',
    },
    {
        id: 45,
        order_id: '60931',
        order_date: '27-Jan-2019',
        order_time: '11:31 PM',
        payment_status: 'Awaiting Authorization',
        total: '$4022.17',
        payment_method: 'Payoneer',
        order_status: 'Delivered',
    },
    {
        id: 46,
        order_id: '2',
        order_date: '12-Jan-2019',
        order_time: '1:01 PM',
        payment_status: 'Payment Failed',
        total: '$7455.30',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 47,
        order_id: '92',
        order_date: '20-Jul-2019',
        order_time: '2:48 PM',
        payment_status: 'Unpaid',
        total: '$192.21',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 48,
        order_id: '937',
        order_date: '05-Apr-2019',
        order_time: '6:06 PM',
        payment_status: 'Payment Failed',
        total: '$4070.53',
        payment_method: 'Visa',
        order_status: 'Shipped',
    },
    {
        id: 49,
        order_id: '3474',
        order_date: '27-Jan-2019',
        order_time: '8:18 PM',
        payment_status: 'Unpaid',
        total: '$2957.29',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 50,
        order_id: '1419',
        order_date: '10-Feb-2019',
        order_time: '12:58 AM',
        payment_status: 'Unpaid',
        total: '$8052.46',
        payment_method: 'Mastercard',
        order_status: 'Shipped',
    },
    {
        id: 51,
        order_id: '763',
        order_date: '16-Feb-2019',
        order_time: '5:36 AM',
        payment_status: 'Unpaid',
        total: '$1424.77',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 52,
        order_id: '2',
        order_date: '12-May-2019',
        order_time: '8:32 PM',
        payment_status: 'Unpaid',
        total: '$2126.47',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 53,
        order_id: '06',
        order_date: '07-Mar-2019',
        order_time: '3:10 AM',
        payment_status: 'Payment Failed',
        total: '$3626.53',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 54,
        order_id: '29608',
        order_date: '18-Jul-2019',
        order_time: '10:03 PM',
        payment_status: 'Awaiting Authorization',
        total: '$4291.42',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 55,
        order_id: '109',
        order_date: '05-Apr-2019',
        order_time: '8:14 AM',
        payment_status: 'Paid',
        total: '$417.32',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 56,
        order_id: '700',
        order_date: '08-Apr-2019',
        order_time: '9:49 AM',
        payment_status: 'Payment Failed',
        total: '$1046.92',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 57,
        order_id: '59297',
        order_date: '06-Feb-2019',
        order_time: '8:49 PM',
        payment_status: 'Paid',
        total: '$8722.68',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 58,
        order_id: '74',
        order_date: '02-Feb-2019',
        order_time: '10:59 PM',
        payment_status: 'Payment Failed',
        total: '$9032.25',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 59,
        order_id: '2',
        order_date: '08-Jun-2019',
        order_time: '10:38 PM',
        payment_status: 'Unpaid',
        total: '$6220.01',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 60,
        order_id: '1375',
        order_date: '12-Jan-2019',
        order_time: '4:07 PM',
        payment_status: 'Unpaid',
        total: '$8482.80',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 61,
        order_id: '65',
        order_date: '26-Jan-2019',
        order_time: '3:23 PM',
        payment_status: 'Awaiting Authorization',
        total: '$1429.24',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 62,
        order_id: '6158',
        order_date: '24-Jan-2019',
        order_time: '4:33 PM',
        payment_status: 'Awaiting Authorization',
        total: '$6894.72',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 63,
        order_id: '47797',
        order_date: '29-May-2019',
        order_time: '7:05 PM',
        payment_status: 'Paid',
        total: '$6970.59',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 64,
        order_id: '7727',
        order_date: '12-Jun-2019',
        order_time: '4:52 AM',
        payment_status: 'Awaiting Authorization',
        total: '$8793.72',
        payment_method: 'Visa',
        order_status: 'Delivered',
    },
    {
        id: 65,
        order_id: '69091',
        order_date: '15-Apr-2019',
        order_time: '2:13 AM',
        payment_status: 'Awaiting Authorization',
        total: '$799.08',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 66,
        order_id: '55320',
        order_date: '29-Jan-2019',
        order_time: '7:47 AM',
        payment_status: 'Payment Failed',
        total: '$8411.65',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 67,
        order_id: '334',
        order_date: '15-Jan-2019',
        order_time: '5:15 PM',
        payment_status: 'Payment Failed',
        total: '$885.00',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 68,
        order_id: '782',
        order_date: '13-Feb-2019',
        order_time: '2:57 PM',
        payment_status: 'Unpaid',
        total: '$8856.16',
        payment_method: 'Mastercard',
        order_status: 'Shipped',
    },
    {
        id: 69,
        order_id: '6036',
        order_date: '30-Apr-2019',
        order_time: '1:29 AM',
        payment_status: 'Unpaid',
        total: '$904.92',
        payment_method: 'Mastercard',
        order_status: 'Shipped',
    },
    {
        id: 70,
        order_id: '2028',
        order_date: '04-Jan-2019',
        order_time: '2:05 PM',
        payment_status: 'Unpaid',
        total: '$4966.59',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 71,
        order_id: '603',
        order_date: '14-Jan-2019',
        order_time: '4:21 AM',
        payment_status: 'Unpaid',
        total: '$2899.05',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 72,
        order_id: '0497',
        order_date: '08-Jun-2019',
        order_time: '2:27 AM',
        payment_status: 'Unpaid',
        total: '$8717.70',
        payment_method: 'Payoneer',
        order_status: 'Shipped',
    },
    {
        id: 73,
        order_id: '635',
        order_date: '15-Jul-2019',
        order_time: '2:51 AM',
        payment_status: 'Paid',
        total: '$5238.61',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 74,
        order_id: '2185',
        order_date: '13-Jan-2019',
        order_time: '8:06 PM',
        payment_status: 'Unpaid',
        total: '$620.06',
        payment_method: 'Visa',
        order_status: 'Shipped',
    },
    {
        id: 75,
        order_id: '235',
        order_date: '28-Jun-2019',
        order_time: '8:22 AM',
        payment_status: 'Paid',
        total: '$8280.55',
        payment_method: 'Paypal',
        order_status: 'Processing',
    },
    {
        id: 76,
        order_id: '121',
        order_date: '09-Apr-2019',
        order_time: '4:41 PM',
        payment_status: 'Payment Failed',
        total: '$8483.16',
        payment_method: 'Payoneer',
        order_status: 'Cancelled',
    },
    {
        id: 77,
        order_id: '9288',
        order_date: '17-Jun-2019',
        order_time: '6:17 PM',
        payment_status: 'Paid',
        total: '$5638.00',
        payment_method: 'Credit Card',
        order_status: 'Delivered',
    },
    {
        id: 78,
        order_id: '4',
        order_date: '27-May-2019',
        order_time: '8:31 PM',
        payment_status: 'Paid',
        total: '$3600.90',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
    {
        id: 79,
        order_id: '98',
        order_date: '18-Jul-2019',
        order_time: '6:25 AM',
        payment_status: 'Awaiting Authorization',
        total: '$7017.32',
        payment_method: 'Visa',
        order_status: 'Cancelled',
    },
    {
        id: 80,
        order_id: '2',
        order_date: '21-Jul-2019',
        order_time: '11:32 AM',
        payment_status: 'Payment Failed',
        total: '$4923.75',
        payment_method: 'Visa',
        order_status: 'Processing',
    },
    {
        id: 81,
        order_id: '18652',
        order_date: '17-Mar-2019',
        order_time: '5:16 AM',
        payment_status: 'Awaiting Authorization',
        total: '$7781.30',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 82,
        order_id: '2154',
        order_date: '16-Jul-2019',
        order_time: '8:49 PM',
        payment_status: 'Unpaid',
        total: '$7772.35',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
    {
        id: 83,
        order_id: '127',
        order_date: '18-Apr-2019',
        order_time: '8:00 PM',
        payment_status: 'Unpaid',
        total: '$8074.16',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 84,
        order_id: '8866',
        order_date: '13-May-2019',
        order_time: '3:53 PM',
        payment_status: 'Unpaid',
        total: '$1769.78',
        payment_method: 'Mastercard',
        order_status: 'Cancelled',
    },
    {
        id: 85,
        order_id: '3',
        order_date: '28-Mar-2019',
        order_time: '9:37 PM',
        payment_status: 'Awaiting Authorization',
        total: '$8387.41',
        payment_method: 'Payoneer',
        order_status: 'Processing',
    },
    {
        id: 86,
        order_id: '9499',
        order_date: '25-Jan-2019',
        order_time: '5:56 PM',
        payment_status: 'Unpaid',
        total: '$1575.43',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 87,
        order_id: '905',
        order_date: '08-Jun-2019',
        order_time: '1:47 PM',
        payment_status: 'Payment Failed',
        total: '$6732.83',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 88,
        order_id: '3',
        order_date: '11-Jun-2019',
        order_time: '2:29 PM',
        payment_status: 'Unpaid',
        total: '$8606.47',
        payment_method: 'Paypal',
        order_status: 'Cancelled',
    },
    {
        id: 89,
        order_id: '23556',
        order_date: '21-Jan-2019',
        order_time: '5:00 PM',
        payment_status: 'Awaiting Authorization',
        total: '$7765.50',
        payment_method: 'Payoneer',
        order_status: 'Cancelled',
    },
    {
        id: 90,
        order_id: '625',
        order_date: '27-Jan-2019',
        order_time: '12:37 PM',
        payment_status: 'Paid',
        total: '$3732.00',
        payment_method: 'Mastercard',
        order_status: 'Shipped',
    },
    {
        id: 91,
        order_id: '6',
        order_date: '23-Jul-2019',
        order_time: '6:04 PM',
        payment_status: 'Payment Failed',
        total: '$7194.17',
        payment_method: 'Mastercard',
        order_status: 'Delivered',
    },
    {
        id: 92,
        order_id: '2808',
        order_date: '06-Jun-2019',
        order_time: '10:41 PM',
        payment_status: 'Paid',
        total: '$1181.92',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 93,
        order_id: '9313',
        order_date: '08-May-2019',
        order_time: '8:10 AM',
        payment_status: 'Paid',
        total: '$370.72',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 94,
        order_id: '66',
        order_date: '24-Jan-2019',
        order_time: '12:30 AM',
        payment_status: 'Unpaid',
        total: '$3398.52',
        payment_method: 'Paypal',
        order_status: 'Shipped',
    },
    {
        id: 95,
        order_id: '5',
        order_date: '04-Jun-2019',
        order_time: '7:23 PM',
        payment_status: 'Paid',
        total: '$8872.94',
        payment_method: 'Paypal',
        order_status: 'Delivered',
    },
    {
        id: 96,
        order_id: '4',
        order_date: '21-May-2019',
        order_time: '6:13 AM',
        payment_status: 'Payment Failed',
        total: '$6897.83',
        payment_method: 'Mastercard',
        order_status: 'Processing',
    },
    {
        id: 97,
        order_id: '7160',
        order_date: '08-Apr-2019',
        order_time: '10:49 PM',
        payment_status: 'Unpaid',
        total: '$4432.29',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
    {
        id: 98,
        order_id: '10509',
        order_date: '05-Jun-2019',
        order_time: '7:54 PM',
        payment_status: 'Unpaid',
        total: '$6381.03',
        payment_method: 'Credit Card',
        order_status: 'Shipped',
    },
    {
        id: 99,
        order_id: '025',
        order_date: '31-May-2019',
        order_time: '8:50 PM',
        payment_status: 'Awaiting Authorization',
        total: '$197.45',
        payment_method: 'Payoneer',
        order_status: 'Processing',
    },
    {
        id: 100,
        order_id: '16529',
        order_date: '01-Jul-2019',
        order_time: '6:04 AM',
        payment_status: 'Payment Failed',
        total: '$3337.15',
        payment_method: 'Credit Card',
        order_status: 'Cancelled',
    },
];

const customers: Customer[] = [{
    id: 1,
    name: 'Calhoun Jurisch',
    phone: '237-960-4150',
    email: 'cjurisch0@virginia.edu',
    location: 'Costa Rica',
    created_on: '11/17/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 2,
    name: 'Axe Rulton',
    phone: '793-400-7003',
    email: 'arulton1@google.com.hk',
    location: 'Slovenia',
    created_on: '05/18/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 3,
    name: 'Kalindi Robjant',
    phone: '847-272-2783',
    email: 'krobjant2@networkadvertising.org',
    location: 'Ukraine',
    created_on: '07/21/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 4,
    name: 'Barnabas Dunridge',
    phone: '259-691-9956',
    email: 'bdunridge3@narod.ru',
    location: 'China',
    created_on: '01/25/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 5,
    name: 'Billy Petrus',
    phone: '544-342-6594',
    email: 'bpetrus4@harvard.edu',
    location: 'Mauritius',
    created_on: '11/28/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 6,
    name: 'Karly Gleave',
    phone: '776-411-2058',
    email: 'kgleave5@craigslist.org',
    location: 'Indonesia',
    created_on: '08/29/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 7,
    name: 'Jeffie Kirkland',
    phone: '533-278-3816',
    email: 'jkirkland6@twitter.com',
    location: 'Indonesia',
    created_on: '02/09/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 8,
    name: 'Tierney Iorizzi',
    phone: '914-298-7354',
    email: 'tiorizzi7@ask.com',
    location: 'Macedonia',
    created_on: '06/14/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 9,
    name: 'Brena Fosh',
    phone: '883-143-9328',
    email: 'bfosh8@wikipedia.org',
    location: 'Russia',
    created_on: '08/26/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 10,
    name: 'Caye Maymand',
    phone: '312-776-6360',
    email: 'cmaymand9@freewebs.com',
    location: 'Sweden',
    created_on: '10/15/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 11,
    name: 'Delinda Angove',
    phone: '860-746-2368',
    email: 'dangovea@noaa.gov',
    location: 'China',
    created_on: '01/26/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 12,
    name: 'Dasie Keelin',
    phone: '255-652-9988',
    email: 'dkeelinb@google.co.jp',
    location: 'Sweden',
    created_on: '02/19/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 13,
    name: 'Paule Henderson',
    phone: '895-805-4051',
    email: 'phendersonc@scientificamerican.com',
    location: 'Poland',
    created_on: '12/27/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 14,
    name: 'Erl Mullan',
    phone: '351-466-6655',
    email: 'emulland@sbwire.com',
    location: 'Czech Republic',
    created_on: '05/20/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 15,
    name: 'Oberon McGilvray',
    phone: '877-345-7651',
    email: 'omcgilvraye@parallels.com',
    location: 'China',
    created_on: '07/02/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 16,
    name: 'Jaymee Spittall',
    phone: '131-439-5707',
    email: 'jspittallf@google.es',
    location: 'Russia',
    created_on: '02/03/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 17,
    name: 'Ardine Purvess',
    phone: '378-783-2226',
    email: 'apurvessg@skype.com',
    location: 'Thailand',
    created_on: '02/12/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 18,
    name: 'Berti Schurcke',
    phone: '576-605-1162',
    email: 'bschurckeh@yelp.com',
    location: 'Indonesia',
    created_on: '08/14/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 19,
    name: 'Lois Haggarth',
    phone: '436-665-4335',
    email: 'lhaggarthi@mail.ru',
    location: 'Indonesia',
    created_on: '01/02/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 20,
    name: 'Lidia Catonne',
    phone: '546-678-6108',
    email: 'lcatonnej@wikimedia.org',
    location: 'France',
    created_on: '12/27/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 21,
    name: 'Ilse McSkeagan',
    phone: '912-775-1755',
    email: 'imcskeagank@cbc.ca',
    location: 'Brazil',
    created_on: '12/22/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 22,
    name: 'Shelbi Scoffins',
    phone: '896-107-1331',
    email: 'sscoffinsl@ucoz.com',
    location: 'Brazil',
    created_on: '01/19/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 23,
    name: 'Herschel Richemond',
    phone: '979-268-9701',
    email: 'hrichemondm@hp.com',
    location: 'South Korea',
    created_on: '10/20/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 24,
    name: 'Manda Kidder',
    phone: '408-677-8641',
    email: 'mkiddern@slashdot.org',
    location: 'United States',
    created_on: '03/16/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 25,
    name: 'Carlynne Moffatt',
    phone: '785-944-0565',
    email: 'cmoffatto@google.com.au',
    location: 'China',
    created_on: '07/14/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 26,
    name: 'Chris Hailey',
    phone: '771-443-8390',
    email: 'chaileyp@salon.com',
    location: 'Greece',
    created_on: '01/08/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 27,
    name: 'Ronny Durbyn',
    phone: '481-835-8556',
    email: 'rdurbynq@studiopress.com',
    location: 'Russia',
    created_on: '11/26/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 28,
    name: 'Gale Tunnah',
    phone: '744-794-3069',
    email: 'gtunnahr@nymag.com',
    location: 'Japan',
    created_on: '05/01/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 29,
    name: 'Winnifred Laval',
    phone: '243-155-1749',
    email: 'wlavals@sciencedirect.com',
    location: 'Japan',
    created_on: '11/11/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 30,
    name: 'Kylen Meenan',
    phone: '813-163-5813',
    email: 'kmeenant@mapy.cz',
    location: 'Mongolia',
    created_on: '06/04/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 31,
    name: 'Ethan Boskell',
    phone: '250-811-4195',
    email: 'eboskellu@prlog.org',
    location: 'Colombia',
    created_on: '11/23/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 32,
    name: 'Haslett Lillo',
    phone: '188-768-7390',
    email: 'hlillov@globo.com',
    location: 'Sweden',
    created_on: '12/17/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 33,
    name: 'Onofredo Payn',
    phone: '312-937-6093',
    email: 'opaynw@ted.com',
    location: 'Israel',
    created_on: '05/19/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 34,
    name: 'Maybelle Hallward',
    phone: '959-223-4786',
    email: 'mhallwardx@si.edu',
    location: 'Indonesia',
    created_on: '03/03/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 35,
    name: 'Rourke Winchcombe',
    phone: '725-326-6328',
    email: 'rwinchcombey@cafepress.com',
    location: 'China',
    created_on: '08/04/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 36,
    name: 'Nahum Caps',
    phone: '223-829-1794',
    email: 'ncapsz@businessweek.com',
    location: 'Indonesia',
    created_on: '04/08/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 37,
    name: 'Buddy Langlais',
    phone: '642-402-9216',
    email: 'blanglais10@dedecms.com',
    location: 'Slovenia',
    created_on: '03/13/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 38,
    name: 'Terrell Whichelow',
    phone: '667-300-8162',
    email: 'twhichelow11@bandcamp.com',
    location: 'Czech Republic',
    created_on: '11/16/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 39,
    name: 'Edie Alwen',
    phone: '843-488-3319',
    email: 'ealwen12@instagram.com',
    location: 'Portugal',
    created_on: '12/31/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 40,
    name: 'Shannan Fontelles',
    phone: '157-303-2312',
    email: 'sfontelles13@newyorker.com',
    location: 'China',
    created_on: '07/06/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 41,
    name: 'Eran Beckett',
    phone: '183-885-3780',
    email: 'ebeckett14@mapy.cz',
    location: 'Finland',
    created_on: '08/05/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 42,
    name: 'Cyndie Swigger',
    phone: '606-697-8910',
    email: 'cswigger15@4shared.com',
    location: 'Peru',
    created_on: '01/21/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 43,
    name: 'Hoyt Loudon',
    phone: '408-213-4454',
    email: 'hloudon16@stumbleupon.com',
    location: 'United States',
    created_on: '11/06/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 44,
    name: 'Ned Bygreaves',
    phone: '323-496-9901',
    email: 'nbygreaves17@dmoz.org',
    location: 'Philippines',
    created_on: '05/30/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 45,
    name: 'Kayne Lavers',
    phone: '291-124-4659',
    email: 'klavers18@istockphoto.com',
    location: 'China',
    created_on: '01/23/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 46,
    name: 'Helen Ricardo',
    phone: '914-578-2934',
    email: 'hricardo19@bloglovin.com',
    location: 'Indonesia',
    created_on: '06/28/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 47,
    name: 'Hodge Staunton',
    phone: '263-305-9530',
    email: 'hstaunton1a@tuttocitta.it',
    location: 'Ukraine',
    created_on: '03/22/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 48,
    name: 'Laina Extence',
    phone: '164-944-0339',
    email: 'lextence1b@mail.ru',
    location: 'China',
    created_on: '12/14/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 49,
    name: 'Kirsti Godspede',
    phone: '966-450-2447',
    email: 'kgodspede1c@cdc.gov',
    location: 'France',
    created_on: '03/16/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 50,
    name: 'Alisander Pane',
    phone: '483-378-0064',
    email: 'apane1d@mac.com',
    location: 'Portugal',
    created_on: '09/21/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 51,
    name: 'Xever Faircley',
    phone: '741-905-3979',
    email: 'xfaircley1e@cargocollective.com',
    location: 'Croatia',
    created_on: '07/17/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 52,
    name: 'Matthiew Halms',
    phone: '462-610-2978',
    email: 'mhalms1f@vistaprint.com',
    location: 'Japan',
    created_on: '11/06/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 53,
    name: 'Edlin Kornyakov',
    phone: '560-901-0423',
    email: 'ekornyakov1g@census.gov',
    location: 'Indonesia',
    created_on: '01/08/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 54,
    name: 'Nara Marder',
    phone: '435-664-3795',
    email: 'nmarder1h@symantec.com',
    location: 'China',
    created_on: '01/14/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 55,
    name: 'Elton Falla',
    phone: '843-738-6361',
    email: 'efalla1i@bandcamp.com',
    location: 'Indonesia',
    created_on: '10/10/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 56,
    name: 'Andre Stonary',
    phone: '687-744-0791',
    email: 'astonary1j@prlog.org',
    location: 'China',
    created_on: '02/06/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 57,
    name: 'Elinore Moquin',
    phone: '100-493-5099',
    email: 'emoquin1k@surveymonkey.com',
    location: 'Indonesia',
    created_on: '10/23/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 58,
    name: 'Carla Coddington',
    phone: '294-344-6782',
    email: 'ccoddington1l@studiopress.com',
    location: 'Croatia',
    created_on: '01/31/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 59,
    name: 'Moses Lunk',
    phone: '292-502-1902',
    email: 'mlunk1m@sitemeter.com',
    location: 'Poland',
    created_on: '02/24/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 60,
    name: 'Ginnifer McKyrrelly',
    phone: '322-731-8053',
    email: 'gmckyrrelly1n@is.gd',
    location: 'Portugal',
    created_on: '03/19/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 61,
    name: 'Nicki Ozintsev',
    phone: '382-167-5417',
    email: 'nozintsev1o@mayoclinic.com',
    location: 'Chile',
    created_on: '01/14/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 62,
    name: 'Carlo Nursey',
    phone: '590-342-6954',
    email: 'cnursey1p@msu.edu',
    location: 'Nigeria',
    created_on: '03/08/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 63,
    name: 'Korey Berney',
    phone: '823-383-1005',
    email: 'kberney1q@businessweek.com',
    location: 'Indonesia',
    created_on: '01/11/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 64,
    name: 'Mendie McKillop',
    phone: '133-334-9895',
    email: 'mmckillop1r@netvibes.com',
    location: 'Mexico',
    created_on: '12/19/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 65,
    name: 'Harli Cosser',
    phone: '571-278-6061',
    email: 'hcosser1s@earthlink.net',
    location: 'Egypt',
    created_on: '12/20/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 66,
    name: 'Trude Rusling',
    phone: '383-289-3482',
    email: 'trusling1t@linkedin.com',
    location: 'Kazakhstan',
    created_on: '06/18/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 67,
    name: 'Kele Campling',
    phone: '935-534-6058',
    email: 'kcampling1u@unesco.org',
    location: 'Nigeria',
    created_on: '05/23/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 68,
    name: 'Demeter Hearons',
    phone: '462-678-9546',
    email: 'dhearons1v@timesonline.co.uk',
    location: 'Portugal',
    created_on: '07/08/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 69,
    name: 'Demetria Popov',
    phone: '906-394-8455',
    email: 'dpopov1w@cornell.edu',
    location: 'Japan',
    created_on: '05/12/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 70,
    name: 'Annelise Starmont',
    phone: '695-736-3251',
    email: 'astarmont1x@utexas.edu',
    location: 'Nigeria',
    created_on: '07/27/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 71,
    name: 'Edik Haresign',
    phone: '317-163-6552',
    email: 'eharesign1y@businessinsider.com',
    location: 'China',
    created_on: '01/21/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 72,
    name: 'Leandra Pendergrast',
    phone: '409-475-3428',
    email: 'lpendergrast1z@mediafire.com',
    location: 'Indonesia',
    created_on: '01/17/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 73,
    name: 'Rogerio Wallwork',
    phone: '606-354-5837',
    email: 'rwallwork20@nydailynews.com',
    location: 'South Africa',
    created_on: '11/06/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 74,
    name: 'Cos Mostyn',
    phone: '906-366-4157',
    email: 'cmostyn21@squarespace.com',
    location: 'Indonesia',
    created_on: '03/28/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 75,
    name: 'Randolph Tortice',
    phone: '865-723-6671',
    email: 'rtortice22@odnoklassniki.ru',
    location: 'Poland',
    created_on: '11/07/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 76,
    name: 'Leena Francescotti',
    phone: '817-664-9710',
    email: 'lfrancescotti23@people.com.cn',
    location: 'Ukraine',
    created_on: '09/27/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 77,
    name: 'Elspeth Liven',
    phone: '793-469-6899',
    email: 'eliven24@redcross.org',
    location: 'Philippines',
    created_on: '06/20/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 78,
    name: 'Clair Zoren',
    phone: '601-779-9284',
    email: 'czoren25@biglobe.ne.jp',
    location: 'Philippines',
    created_on: '10/01/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 79,
    name: 'Atlante Renahan',
    phone: '477-537-4015',
    email: 'arenahan26@ifeng.com',
    location: 'Greece',
    created_on: '09/12/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 80,
    name: 'Enrika Lemmertz',
    phone: '441-409-1283',
    email: 'elemmertz27@toplist.cz',
    location: 'Japan',
    created_on: '03/16/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 81,
    name: 'Paige Moral',
    phone: '670-172-7193',
    email: 'pmoral28@ning.com',
    location: 'Philippines',
    created_on: '12/26/2018',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 82,
    name: 'Fayth Dibbin',
    phone: '442-584-6949',
    email: 'fdibbin29@live.com',
    location: 'Myanmar',
    created_on: '10/14/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 83,
    name: 'Gloria Musso',
    phone: '198-187-8880',
    email: 'gmusso2a@wordpress.org',
    location: 'Botswana',
    created_on: '09/17/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 84,
    name: 'Rene Dovington',
    phone: '116-633-6853',
    email: 'rdovington2b@163.com',
    location: 'China',
    created_on: '05/10/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 85,
    name: 'Wilow Brainsby',
    phone: '580-841-0171',
    email: 'wbrainsby2c@ask.com',
    location: 'China',
    created_on: '03/29/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 86,
    name: 'Isidore Borkett',
    phone: '872-725-3021',
    email: 'iborkett2d@umn.edu',
    location: 'China',
    created_on: '03/18/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 87,
    name: 'Jethro Laye',
    phone: '386-684-1566',
    email: 'jlaye2e@oracle.com',
    location: 'Sweden',
    created_on: '06/07/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 88,
    name: 'Grannie Patriche',
    phone: '156-254-2399',
    email: 'gpatriche2f@usatoday.com',
    location: 'Indonesia',
    created_on: '05/11/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 89,
    name: 'Jacynth Goundsy',
    phone: '339-392-1915',
    email: 'jgoundsy2g@goo.ne.jp',
    location: 'Malaysia',
    created_on: '06/12/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 90,
    name: 'Ezechiel Golsthorp',
    phone: '978-712-8471',
    email: 'egolsthorp2h@creativecommons.org',
    location: 'Russia',
    created_on: '06/27/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 91,
    name: 'Ignace O\'Loughane',
    phone: '453-455-7536',
    email: 'ioloughane2i@home.pl',
    location: 'Philippines',
    created_on: '09/21/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 92,
    name: 'Stanleigh Leonarde',
    phone: '689-488-3261',
    email: 'sleonarde2j@nytimes.com',
    location: 'China',
    created_on: '05/16/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 93,
    name: 'Tammy Manhare',
    phone: '517-445-7695',
    email: 'tmanhare2k@g.co',
    location: 'Thailand',
    created_on: '09/18/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}, {
    id: 94,
    name: 'Kingston Bakster',
    phone: '864-603-2366',
    email: 'kbakster2l@mysql.com',
    location: 'Indonesia',
    created_on: '01/16/2019',
    status: 'Active',
    avatar: 'assets/images/users/avatar-3.jpg'
}, {
    id: 95,
    name: 'Chip Panchin',
    phone: '848-290-0668',
    email: 'cpanchin2m@goo.gl',
    location: 'Indonesia',
    created_on: '08/30/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-4.jpg'
}, {
    id: 96,
    name: 'Laurel Cremen',
    phone: '268-241-0447',
    email: 'lcremen2n@moonfruit.com',
    location: 'Guinea',
    created_on: '09/28/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-5.jpg'
}, {
    id: 97,
    name: 'Cami Enos',
    phone: '851-231-1785',
    email: 'cenos2o@abc.net.au',
    location: 'China',
    created_on: '06/29/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-6.jpg'
}, {
    id: 98,
    name: 'Dedie Seldon',
    phone: '857-931-8976',
    email: 'dseldon2p@vimeo.com',
    location: 'Indonesia',
    created_on: '07/13/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-7.jpg'
}, {
    id: 99,
    name: 'Trip Austwick',
    phone: '648-514-6247',
    email: 'taustwick2q@meetup.com',
    location: 'Brazil',
    created_on: '04/28/2019',
    status: 'Blocked',
    avatar: 'assets/images/users/avatar-1.jpg'
}, {
    id: 100,
    name: 'Frederich Kettles',
    phone: '703-126-2946',
    email: 'fkettles2r@miitbeian.gov.cn',
    location: 'Peru',
    created_on: '11/09/2018',
    status: 'Active',
    avatar: 'assets/images/users/avatar-2.jpg'
}];

const sellers: Seller[] = [{
    id: 1,
    name: 'Vinnie Chicchelli',
    store: 'Caen',
    image: 'assets/images/users/avatar-1.jpg',
    products: 488,
    balance: '$106.27',
    created_on: '05/04/2019',
}, {
    id: 2,
    name: 'Archibald Parades',
    store: 'Hengxi',
    image: 'assets/images/users/avatar-2.jpg',
    products: 51,
    balance: '$36319.37',
    created_on: '06/30/2019'
}, {
    id: 3,
    name: 'Blair Root',
    store: 'Phu Luang',
    image: 'assets/images/users/avatar-3.jpg',
    products: 334,
    balance: '$11249.62',
    created_on: '11/28/2018'
}, {
    id: 4,
    name: 'Mariel Savile',
    store: 'Rio das Pedras',
    image: 'assets/images/users/avatar-4.jpg',
    products: 10,
    balance: '$16584.31',
    created_on: '08/26/2019'
}, {
    id: 5,
    name: 'Levon Cowthart',
    store: 'Jiaotang',
    image: 'assets/images/users/avatar-5.jpg',
    products: 151,
    balance: '$41178.37',
    created_on: '09/16/2019'
}, {
    id: 6,
    name: 'Darnall Aisman',
    store: 'Kamuli',
    image: 'assets/images/users/avatar-6.jpg',
    products: 197,
    balance: '$11096.82',
    created_on: '01/11/2019'
}, {
    id: 7,
    name: 'Fred Willicott',
    store: 'Zhavoronki',
    image: 'assets/images/users/avatar-7.jpg',
    products: 229,
    balance: '$7143.11',
    created_on: '06/07/2019'
}, {
    id: 8,
    name: 'Jannelle Tuny',
    store: 'Lewoluo',
    image: 'assets/images/users/avatar-1.jpg',
    products: 432,
    balance: '$49819.50',
    created_on: '07/04/2019'
}, {
    id: 9,
    name: 'Dominique Stathers',
    store: 'Vilarinho',
    image: 'assets/images/users/avatar-2.jpg',
    products: 170,
    balance: '$32533.98',
    created_on: '09/07/2019'
}, {
    id: 10,
    name: 'Lilas Laytham',
    store: 'New Leyte',
    image: 'assets/images/users/avatar-3.jpg',
    products: 261,
    balance: '$1631.49',
    created_on: '10/24/2019'
}, {
    id: 11,
    name: 'Cece McOmish',
    store: 'Toronto',
    image: 'assets/images/users/avatar-4.jpg',
    products: 195,
    balance: '$38287.45',
    created_on: '02/02/2019'
}, {
    id: 12,
    name: 'Cordie Domenichini',
    store: 'Fier',
    image: 'assets/images/users/avatar-5.jpg',
    products: 47,
    balance: '$4046.11',
    created_on: '10/22/2019'
}, {
    id: 13,
    name: 'Concettina Coite',
    store: 'Tibro',
    image: 'assets/images/users/avatar-6.jpg',
    products: 9,
    balance: '$8922.46',
    created_on: '01/21/2019'
}, {
    id: 14,
    name: 'Martica Liffey',
    store: 'Mojkovac',
    image: 'assets/images/users/avatar-7.jpg',
    products: 386,
    balance: '$30648.35',
    created_on: '06/08/2019'
}, {
    id: 15,
    name: 'Edna Posselwhite',
    store: 'Macklin',
    image: 'assets/images/users/avatar-1.jpg',
    products: 126,
    balance: '$41395.98',
    created_on: '06/30/2019'
}, {
    id: 16,
    name: 'Keelia Hulkes',
    store: 'Chicago',
    image: 'assets/images/users/avatar-2.jpg',
    products: 343,
    balance: '$20206.14',
    created_on: '11/22/2018'
}, {
    id: 17,
    name: 'Jeanette Gehringer',
    store: 'Cergy-Pontoise',
    image: 'assets/images/users/avatar-3.jpg',
    products: 289,
    balance: '$16531.59',
    created_on: '07/16/2019'
}, {
    id: 18,
    name: 'Steffane Spellissy',
    store: 'Valera',
    image: 'assets/images/users/avatar-4.jpg',
    products: 179,
    balance: '$11265.30',
    created_on: '08/15/2019'
}, {
    id: 19,
    name: 'Delcine Cassin',
    store: 'Ferme-Neuve',
    image: 'assets/images/users/avatar-5.jpg',
    products: 380,
    balance: '$48892.20',
    created_on: '01/20/2019'
}, {
    id: 20,
    name: 'Bibbie Francescuccio',
    store: 'Mosjøen',
    image: 'assets/images/users/avatar-6.jpg',
    products: 119,
    balance: '$48382.04',
    created_on: '08/01/2019'
}, {
    id: 21,
    name: 'Reece Gergler',
    store: 'Naguilian',
    image: 'assets/images/users/avatar-7.jpg',
    products: 17,
    balance: '$9834.61',
    created_on: '07/08/2019'
}, {
    id: 22,
    name: 'Felic Gilluley',
    store: 'Neietsu',
    image: 'assets/images/users/avatar-1.jpg',
    products: 198,
    balance: '$43234.51',
    created_on: '01/18/2019'
}, {
    id: 23,
    name: 'Jemie Mannooch',
    store: 'Banjarsari',
    image: 'assets/images/users/avatar-2.jpg',
    products: 105,
    balance: '$21347.58',
    created_on: '10/15/2019'
}, {
    id: 24,
    name: 'Manny Beaze',
    store: 'Rokiciny',
    image: 'assets/images/users/avatar-3.jpg',
    products: 246,
    balance: '$9881.89',
    created_on: '01/27/2019'
}, {
    id: 25,
    name: 'Rubetta Maliphant',
    store: 'Jiaoxie',
    image: 'assets/images/users/avatar-4.jpg',
    products: 479,
    balance: '$7622.76',
    created_on: '11/11/2018'
}, {
    id: 26,
    name: 'Dwight Pinnocke',
    store: 'Las Palmas',
    image: 'assets/images/users/avatar-5.jpg',
    products: 83,
    balance: '$32601.27',
    created_on: '03/24/2019'
}, {
    id: 27,
    name: 'Wilburt Anyon',
    store: 'Dogonbadan',
    image: 'assets/images/users/avatar-6.jpg',
    products: 244,
    balance: '$29719.61',
    created_on: '02/14/2019'
}, {
    id: 28,
    name: 'Dud Deville',
    store: 'Pewel Wielka',
    image: 'assets/images/users/avatar-7.jpg',
    products: 87,
    balance: '$514.77',
    created_on: '07/22/2019'
}, {
    id: 29,
    name: 'Alyssa Chalcot',
    store: 'Morohongō',
    image: 'assets/images/users/avatar-1.jpg',
    products: 111,
    balance: '$7191.85',
    created_on: '03/08/2019'
}, {
    id: 30,
    name: 'Gawen Placido',
    store: 'Rauco',
    image: 'assets/images/users/avatar-2.jpg',
    products: 67,
    balance: '$31573.89',
    created_on: '01/21/2019'
}, {
    id: 31,
    name: 'Gallagher Treweke',
    store: 'Ożarowice',
    image: 'assets/images/users/avatar-3.jpg',
    products: 91,
    balance: '$21165.83',
    created_on: '06/05/2019'
}, {
    id: 32,
    name: 'Noelyn Jaulme',
    store: 'Kuršėnai',
    image: 'assets/images/users/avatar-4.jpg',
    products: 142,
    balance: '$27699.47',
    created_on: '07/01/2019'
}, {
    id: 33,
    name: 'Neill MacAllester',
    store: 'Hua Sai',
    image: 'assets/images/users/avatar-5.jpg',
    products: 276,
    balance: '$25345.41',
    created_on: '11/24/2018'
}, {
    id: 34,
    name: 'Ham Cocklie',
    store: 'Melgar',
    image: 'assets/images/users/avatar-6.jpg',
    products: 110,
    balance: '$17457.62',
    created_on: '05/31/2019'
}, {
    id: 35,
    name: 'Brok Bielfelt',
    store: 'Jinshi',
    image: 'assets/images/users/avatar-7.jpg',
    products: 253,
    balance: '$20281.53',
    created_on: '05/21/2019'
}, {
    id: 36,
    name: 'Dasha Kirsche',
    store: 'Zhangjiabao',
    image: 'assets/images/users/avatar-1.jpg',
    products: 482,
    balance: '$44406.71',
    created_on: '09/25/2019'
}, {
    id: 37,
    name: 'Bobine MacLoughlin',
    store: 'Pomiechówek',
    image: 'assets/images/users/avatar-2.jpg',
    products: 160,
    balance: '$32807.95',
    created_on: '05/24/2019'
}, {
    id: 38,
    name: 'Shepperd Wallwork',
    store: 'Barretos',
    image: 'assets/images/users/avatar-3.jpg',
    products: 352,
    balance: '$40525.09',
    created_on: '04/02/2019'
}, {
    id: 39,
    name: 'Poppy Ismail',
    store: 'Dapdap',
    image: 'assets/images/users/avatar-4.jpg',
    products: 374,
    balance: '$12504.53',
    created_on: '12/31/2018'
}, {
    id: 40,
    name: 'Alethea Sowerby',
    store: 'Jinshiqiao',
    image: 'assets/images/users/avatar-5.jpg',
    products: 34,
    balance: '$7362.71',
    created_on: '08/06/2019'
}, {
    id: 41,
    name: 'Rosalinde Deabill',
    store: '‘Ayn al Bayḑā',
    image: 'assets/images/users/avatar-6.jpg',
    products: 317,
    balance: '$18495.19',
    created_on: '09/22/2019'
}, {
    id: 42,
    name: 'Alano Klezmski',
    store: 'Donegal',
    image: 'assets/images/users/avatar-7.jpg',
    products: 379,
    balance: '$9207.95',
    created_on: '02/21/2019'
}, {
    id: 43,
    name: 'Ennis Pennino',
    store: 'Tucupita',
    image: 'assets/images/users/avatar-1.jpg',
    products: 432,
    balance: '$10264.67',
    created_on: '01/09/2019'
}, {
    id: 44,
    name: 'Chrissy Spellward',
    store: 'Chợ Chu',
    image: 'assets/images/users/avatar-2.jpg',
    products: 239,
    balance: '$22731.79',
    created_on: '08/18/2019'
}, {
    id: 45,
    name: 'Emlen Catley',
    store: 'Heku',
    image: 'assets/images/users/avatar-3.jpg',
    products: 442,
    balance: '$41308.68',
    created_on: '01/22/2019'
}, {
    id: 46,
    name: 'Sorcha Penritt',
    store: 'Bingerville',
    image: 'assets/images/users/avatar-4.jpg',
    products: 102,
    balance: '$47673.61',
    created_on: '08/08/2019'
}, {
    id: 47,
    name: 'Ricoriki Fulham',
    store: 'Estacion',
    image: 'assets/images/users/avatar-5.jpg',
    products: 482,
    balance: '$42290.23',
    created_on: '06/25/2019'
}, {
    id: 48,
    name: 'Shena Eldred',
    store: 'Qinlan',
    image: 'assets/images/users/avatar-6.jpg',
    products: 497,
    balance: '$18412.54',
    created_on: '04/04/2019'
}, {
    id: 49,
    name: 'Lothaire Tingey',
    store: 'Swedru',
    image: 'assets/images/users/avatar-7.jpg',
    products: 336,
    balance: '$24256.62',
    created_on: '10/29/2019'
}, {
    id: 50,
    name: 'Adella Ryce',
    store: 'Sapporo',
    image: 'assets/images/users/avatar-1.jpg',
    products: 6,
    balance: '$33336.89',
    created_on: '01/24/2019'
}, {
    id: 51,
    name: 'Alina McAloren',
    store: 'Trà Vinh',
    image: 'assets/images/users/avatar-2.jpg',
    products: 169,
    balance: '$27512.74',
    created_on: '09/09/2019'
}, {
    id: 52,
    name: 'Danni Hawkins',
    store: 'Jianggao',
    image: 'assets/images/users/avatar-3.jpg',
    products: 336,
    balance: '$11481.46',
    created_on: '05/16/2019'
}, {
    id: 53,
    name: 'Bealle Mulvihill',
    store: 'Peishe',
    image: 'assets/images/users/avatar-4.jpg',
    products: 61,
    balance: '$6137.15',
    created_on: '10/24/2019'
}, {
    id: 54,
    name: 'Danita Autin',
    store: 'Pirapora do Bom Jesus',
    image: 'assets/images/users/avatar-5.jpg',
    products: 85,
    balance: '$30630.99',
    created_on: '06/20/2019'
}, {
    id: 55,
    name: 'Valina Ewbanks',
    store: 'Tamberías',
    image: 'assets/images/users/avatar-6.jpg',
    products: 222,
    balance: '$14141.87',
    created_on: '07/29/2019'
}, {
    id: 56,
    name: 'Lian Kinnock',
    store: 'Nāḩiyat as Sab‘ Biyār',
    image: 'assets/images/users/avatar-7.jpg',
    products: 223,
    balance: '$38191.21',
    created_on: '02/06/2019'
}, {
    id: 57,
    name: 'Jordain Spadotto',
    store: 'Mashava',
    image: 'assets/images/users/avatar-1.jpg',
    products: 368,
    balance: '$22344.55',
    created_on: '10/08/2019'
}, {
    id: 58,
    name: 'Gay Ledley',
    store: 'Potosí',
    image: 'assets/images/users/avatar-2.jpg',
    products: 58,
    balance: '$3176.67',
    created_on: '02/24/2019'
}, {
    id: 59,
    name: 'Emanuele Pendrick',
    store: 'Al ‘Āqir',
    image: 'assets/images/users/avatar-3.jpg',
    products: 299,
    balance: '$8013.45',
    created_on: '04/21/2019'
}, {
    id: 60,
    name: 'Gabi Smythe',
    store: 'Ambarakaraka',
    image: 'assets/images/users/avatar-4.jpg',
    products: 215,
    balance: '$22216.80',
    created_on: '10/11/2019'
}, {
    id: 61,
    name: 'Rick Szepe',
    store: 'Pawitan',
    image: 'assets/images/users/avatar-5.jpg',
    products: 335,
    balance: '$12939.27',
    created_on: '02/10/2019'
}, {
    id: 62,
    name: 'Oralle Yakubovics',
    store: 'Sfax',
    image: 'assets/images/users/avatar-6.jpg',
    products: 421,
    balance: '$22661.70',
    created_on: '08/30/2019'
}, {
    id: 63,
    name: 'Rainer Sapey',
    store: 'Spanish Town',
    image: 'assets/images/users/avatar-7.jpg',
    products: 363,
    balance: '$11556.22',
    created_on: '12/11/2018'
}, {
    id: 64,
    name: 'Malorie Nyland',
    store: 'Baltimore',
    image: 'assets/images/users/avatar-1.jpg',
    products: 385,
    balance: '$14001.56',
    created_on: '12/01/2018'
}, {
    id: 65,
    name: 'Madelin Mathiot',
    store: 'Chiryū',
    image: 'assets/images/users/avatar-2.jpg',
    products: 176,
    balance: '$8423.75',
    created_on: '04/27/2019'
}, {
    id: 66,
    name: 'Wynn De Hooge',
    store: 'Guyam Malaki',
    image: 'assets/images/users/avatar-3.jpg',
    products: 49,
    balance: '$379.46',
    created_on: '04/27/2019'
}, {
    id: 67,
    name: 'Theodora Muggleton',
    store: 'Ban Khlong Bang Sao Thong',
    image: 'assets/images/users/avatar-4.jpg',
    products: 119,
    balance: '$23141.75',
    created_on: '02/18/2019'
}, {
    id: 68,
    name: 'Arther Rhubottom',
    store: 'Gorno Orizari',
    image: 'assets/images/users/avatar-5.jpg',
    products: 411,
    balance: '$1290.09',
    created_on: '06/08/2019'
}, {
    id: 69,
    name: 'Phillipp Fayne',
    store: 'Yeoju',
    image: 'assets/images/users/avatar-6.jpg',
    products: 112,
    balance: '$8829.23',
    created_on: '06/14/2019'
}, {
    id: 70,
    name: 'Reinaldos Mompesson',
    store: 'El Paso',
    image: 'assets/images/users/avatar-7.jpg',
    products: 187,
    balance: '$7242.50',
    created_on: '07/12/2019'
}, {
    id: 71,
    name: 'Laverna Devin',
    store: 'Tacuatí',
    image: 'assets/images/users/avatar-1.jpg',
    products: 320,
    balance: '$6686.58',
    created_on: '03/23/2019'
}, {
    id: 72,
    name: 'Odo Braga',
    store: 'Xiaxindian',
    image: 'assets/images/users/avatar-2.jpg',
    products: 51,
    balance: '$43377.42',
    created_on: '07/21/2019'
}, {
    id: 73,
    name: 'Meggi Gooddy',
    store: 'Panjakent',
    image: 'assets/images/users/avatar-3.jpg',
    products: 422,
    balance: '$33905.80',
    created_on: '04/16/2019'
}, {
    id: 74,
    name: 'Shaina Simonnet',
    store: 'Shuangfeng',
    image: 'assets/images/users/avatar-4.jpg',
    products: 56,
    balance: '$17015.70',
    created_on: '02/28/2019'
}, {
    id: 75,
    name: 'Hobie Tiffney',
    store: 'Pajala',
    image: 'assets/images/users/avatar-5.jpg',
    products: 469,
    balance: '$13849.40',
    created_on: '02/18/2019'
}, {
    id: 76,
    name: 'Matthus Witherspoon',
    store: 'Gabès',
    image: 'assets/images/users/avatar-6.jpg',
    products: 279,
    balance: '$31329.87',
    created_on: '06/15/2019'
}, {
    id: 77,
    name: 'Marnie Mattholie',
    store: 'San Francisco',
    image: 'assets/images/users/avatar-7.jpg',
    products: 88,
    balance: '$20153.32',
    created_on: '11/18/2018'
}, {
    id: 78,
    name: 'Davine Stollmeier',
    store: 'Sujji',
    image: 'assets/images/users/avatar-1.jpg',
    products: 408,
    balance: '$46816.18',
    created_on: '07/13/2019'
}, {
    id: 79,
    name: 'Kimbell Shellsheere',
    store: 'Loja',
    image: 'assets/images/users/avatar-2.jpg',
    products: 329,
    balance: '$27092.48',
    created_on: '05/03/2019'
}, {
    id: 80,
    name: 'Berny Humber',
    store: 'Parlilitan',
    image: 'assets/images/users/avatar-3.jpg',
    products: 89,
    balance: '$32861.20',
    created_on: '03/03/2019'
}, {
    id: 81,
    name: 'Marrilee Bellie',
    store: 'Batang',
    image: 'assets/images/users/avatar-4.jpg',
    products: 473,
    balance: '$44680.73',
    created_on: '09/03/2019'
}, {
    id: 82,
    name: 'Roanne Kenworthy',
    store: 'Maqiu',
    image: 'assets/images/users/avatar-5.jpg',
    products: 349,
    balance: '$13035.80',
    created_on: '05/28/2019'
}, {
    id: 83,
    name: 'Heall Bellow',
    store: 'Portel',
    image: 'assets/images/users/avatar-6.jpg',
    products: 444,
    balance: '$12853.04',
    created_on: '08/11/2019'
}, {
    id: 84,
    name: 'Abigael Kollas',
    store: 'Ban Mai',
    image: 'assets/images/users/avatar-7.jpg',
    products: 342,
    balance: '$37565.22',
    created_on: '08/08/2019'
}, {
    id: 85,
    name: 'Glyn O\'Hengerty',
    store: 'Makapanstad',
    image: 'assets/images/users/avatar-1.jpg',
    products: 430,
    balance: '$35812.35',
    created_on: '07/01/2019'
}, {
    id: 86,
    name: 'Elfrida MacLese',
    store: 'Tembilahan',
    image: 'assets/images/users/avatar-2.jpg',
    products: 185,
    balance: '$44116.11',
    created_on: '12/14/2018'
}, {
    id: 87,
    name: 'Hamish Rowledge',
    store: 'Kumlinge',
    image: 'assets/images/users/avatar-3.jpg',
    products: 182,
    balance: '$24597.03',
    created_on: '01/22/2019'
}, {
    id: 88,
    name: 'Lurleen Hatchman',
    store: 'Carcassonne',
    image: 'assets/images/users/avatar-4.jpg',
    products: 180,
    balance: '$6133.40',
    created_on: '01/02/2019'
}, {
    id: 89,
    name: 'Ryley Yedy',
    store: 'Mişrātah',
    image: 'assets/images/users/avatar-5.jpg',
    products: 225,
    balance: '$47877.45',
    created_on: '03/26/2019'
}, {
    id: 90,
    name: 'Reggie Jollands',
    store: 'Annecy',
    image: 'assets/images/users/avatar-6.jpg',
    products: 340,
    balance: '$49164.92',
    created_on: '05/05/2019'
}, {
    id: 91,
    name: 'Joelly Binns',
    store: 'Kokas',
    image: 'assets/images/users/avatar-7.jpg',
    products: 240,
    balance: '$30363.88',
    created_on: '08/11/2019'
}, {
    id: 92,
    name: 'Geri Dignon',
    store: 'Hrtkovci',
    image: 'assets/images/users/avatar-1.jpg',
    products: 500,
    balance: '$29636.97',
    created_on: '06/16/2019'
}, {
    id: 93,
    name: 'Kate Gautrey',
    store: 'Winburg',
    image: 'assets/images/users/avatar-2.jpg',
    products: 396,
    balance: '$9282.90',
    created_on: '11/28/2018'
}, {
    id: 94,
    name: 'Redford Pautot',
    store: 'Ciganaria',
    image: 'assets/images/users/avatar-3.jpg',
    products: 219,
    balance: '$28715.97',
    created_on: '01/26/2019'
}, {
    id: 95,
    name: 'Townie Camamill',
    store: 'Pekuwon',
    image: 'assets/images/users/avatar-4.jpg',
    products: 55,
    balance: '$38802.54',
    created_on: '06/01/2019'
}, {
    id: 96,
    name: 'Nancey Capun',
    store: 'Toritama',
    image: 'assets/images/users/avatar-5.jpg',
    products: 176,
    balance: '$21427.41',
    created_on: '02/25/2019'
}, {
    id: 97,
    name: 'Garrard Arstingall',
    store: 'Telč',
    image: 'assets/images/users/avatar-6.jpg',
    products: 309,
    balance: '$46545.94',
    created_on: '04/12/2019'
}, {
    id: 98,
    name: 'Pren Braznell',
    store: 'Socorro',
    image: 'assets/images/users/avatar-7.jpg',
    products: 387,
    balance: '$25288.73',
    created_on: '09/17/2019'
}, {
    id: 99,
    name: 'Stafford Harragin',
    store: 'Paihia',
    image: 'assets/images/users/avatar-1.jpg',
    products: 339,
    balance: '$21184.13',
    created_on: '04/16/2019'
}, {
    id: 100,
    name: 'Fleming Rucklesse',
    store: 'Ad Dīwānīyah',
    image: 'assets/images/users/avatar-2.jpg',
    products: 289,
    balance: '$46811.38',
    created_on: '07/21/2019'
}];

const cartItems: CartItem[] = [
    {
        id: 1,
        image: 'assets/images/products/product-1.jpg',
        name: 'Amazing Modern Chair',
        size: 'Large',
        color: 'Light Green',
        price: 148.66,
        qty: 5,
        total: 743.3,
    },
    {
        id: 2,
        image: 'assets/images/products/product-2.jpg',
        name: 'Biblio Plastic Armchair',
        size: 'Small',
        color: 'Brown',
        price: 99,
        qty: 2,
        total: 198.0,
    },
    {
        id: 3,
        image: 'assets/images/products/product-3.jpg',
        name: 'Designer Awesome Chair',
        size: 'Medium',
        color: 'Green',
        price: 49.99,
        qty: 3,
        total: 499.9,
    },
    {
        id: 4,
        image: 'assets/images/products/product-4.jpg',
        name: 'Unpowered aircraft',
        size: 'Large',
        color: 'White',
        price: 129.99,
        qty: 1,
        total: 129.99,
    },
];

export { products, orders, customers, sellers, cartItems };
