# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


parameters:
  - name: MFEFolderName
    type: string

stages:
- stage: PRBuild
  displayName: PRBuild
  jobs:
  - template: job-templates/pr-build-job-template.yml
    parameters:
      MFEFolderName: ${{parameters.MFEFolderName}}
      BuildConfiguration: 'build-dev'
      
