import { RouteModel } from "../models/route.model";

export const ROUTEPATHS: RouteModel[] = [
  // Administration
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 1, operationCode: 'OPS01', operationName: 'Create Role',
    resourceId: 1, resourceCode: 'R001', resourceName: 'Role Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 2, operationCode: 'OPS02', operationName: 'Update Role',
    resourceId: 1, resourceCode: 'R001', resourceName: 'Role Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 3, operationCode: 'OPS03', operationName: 'View Role',
    resourceId: 1, resourceCode: 'R001', resourceName: 'Role Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 4, operationCode: 'OPS04', operationName: 'Create Admin',
    resourceId: 2, resourceCode: 'R002', resourceName: 'Admin Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 5, operationCode: 'OPS05', operationName: 'Update Admin',
    resourceId: 2, resourceCode: 'R002', resourceName: 'Admin Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 6, operationCode: 'OPS06', operationName: 'View Admin',
    resourceId: 2, resourceCode: 'R002', resourceName: 'Admin Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 7, operationCode: 'OPS07', operationName: 'Create User',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 8, operationCode: 'OPS08', operationName: 'Update User',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 9, operationCode: 'OPS09', operationName: 'View User',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 10, operationCode: 'OPS10', operationName: 'Create BU Manager',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 11, operationCode: 'OPS11', operationName: 'Update BU Manager',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 12, operationCode: 'OPS12', operationName: 'View BU Manager',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 13, operationCode: 'OPS13', operationName: 'Create Tenant',
    resourceId: 4, resourceCode: 'R004', resourceName: 'Tenant Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 14, operationCode: 'OPS14', operationName: 'Update Tenant',
    resourceId: 4, resourceCode: 'R004', resourceName: 'Tenant Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 15, operationCode: 'OPS15', operationName: 'View Tenant',
    resourceId: 4, resourceCode: 'R004', resourceName: 'Tenant Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  {
    isActive: false,
    key: '', routeName: '', path: '',
    operationId: 19, operationCode: 'OPS19', operationName: 'Update User Status',
    resourceId: 3, resourceCode: 'R003', resourceName: 'User Management',
    moduleId: 1, moduleCode: 'M001', moduleName: 'Administration',
  },
  // MFE-Merchant
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantList', path: '',
    operationId: 20, operationCode: 'OPS20', operationName: 'View Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantDetails', path: 'details',
    operationId: 20, operationCode: 'OPS20', operationName: 'View Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantGroupDetail', path: 'merchant-group-details',
    operationId: 20, operationCode: 'OPS20', operationName: 'View Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'CreateMerchant', path: 'create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantGroupManagement', path: 'merchant-group/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantGroupManagement', path: 'merchant-group/edit',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'GroupSkuManagement', path: 'merchant-group/sku/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'GroupSkuManagement', path: 'merchant-group/sku/edit',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'GroupSkuDetail', path: 'merchant-group/sku/details',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ShopCreate', path: 'shop/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ShopBatchUpload', path: 'shop/create/batch',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'VoucherNumberRuleCreate', path: 'voucher-number-rule/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ContractDetails', path: 'contract/details/:id',
    operationId: 20, operationCode: 'OPS20', operationName: 'View Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ContractCreate', path: 'contract/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ContractEdit', path: 'contract/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Edit Contract',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ContractSKU', path: 'contract/sku/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create SKU',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ContractSKU', path: 'contract/:id/sku/create/draft/details',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create SKU',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'EditSKU', path: 'sku/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Edit Sku',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'AcceptanceLoopCreate', path: 'acceptance-loop/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'AcceptanceLoopEdit', path: 'acceptance-loop/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'UpdateMerchant', path: 'edit',
    operationId: 21, operationCode: 'OPS21', operationName: 'Edit Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'VoucherNumberRuleEdit', path: 'voucher-number-rule/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Edit Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'ShopEdit', path: 'shop/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Edit Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantGroupAcceptanceLoopCreate', path: 'merchant-group/acceptance-loop/create',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  {
    isActive: true,
    key: 'merchants', routeName: 'MerchantGroupAcceptanceLoopEdit', path: 'merchant-group/acceptance-loop/edit/:id',
    operationId: 21, operationCode: 'OPS21', operationName: 'Create Merchant',
    resourceId: 5, resourceCode: 'R005', resourceName: 'Merchant',
    moduleId: 2, moduleCode: 'M002', moduleName: 'Merchant',
  },
  // MFE-Product
  {
    isActive: true,
    key: 'products', routeName: 'ProductList', path: '',
    operationId: 23, operationCode: 'OPS23', operationName: 'View Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'MainProductDetails', path: ':id',
    operationId: 23, operationCode: 'OPS23', operationName: 'View Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'ProductHistory', path: 'product/history/:id',
    operationId: 23, operationCode: 'OPS23', operationName: 'View Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'HistoryDetails', path: 'product/history-details/:id',
    operationId: 23, operationCode: 'OPS23', operationName: 'View Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'CreateProduct', path: 'product/create',
    operationId: 24, operationCode: 'OPS24', operationName: 'Create Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'CreateProduct', path: 'product/create/smart-choice-voucher',
    operationId: 24, operationCode: 'OPS24', operationName: 'Create Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'CreateProduct', path: 'product/create/super-voucher',
    operationId: 24, operationCode: 'OPS24', operationName: 'Create Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/super-voucher/details/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/smart-choice-voucher/details/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/super-voucher/combo/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/smart-choice-voucher/combo/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/super-voucher/pricing-expiry/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/smart-choice-voucher/pricing-expiry/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/super-voucher/template/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/smart-choice-voucher/template/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/super-voucher/advance-settings/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit/smart-choice-voucher/advance-settings/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductDetails', path: 'product/edit-details/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'BatchUpdateProduct', path: 'product/batch-update-product',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditPricingExpiry', path: 'product/edit-pricing/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditProductTemplate', path: 'product/edit-template/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditExternalProperties', path: 'product/edit-external-properties/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditSmartChoiceVoucher', path: 'product/edit/smart-choice-voucher/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'EditSuperVoucher', path: 'product/edit/super-voucher/:id',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'BatchUpdateProductCombo', path: 'product/batch-update-product-combo',
    operationId: 24, operationCode: 'OPS24', operationName: 'Edit Product',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  {
    isActive: true,
    key: 'products', routeName: 'ChildProductsQuotation', path: 'apply-child-products-quotation',
    operationId: 24, operationCode: 'OPS24', operationName: 'Apply Child Products to Quotation',
    resourceId: 6, resourceCode: 'R006', resourceName: 'Product',
    moduleId: 3, moduleCode: 'M003', moduleName: 'Product',
  },
  // MFE-Clinet
  {
    isActive: true,
    key: 'clients', routeName: 'ClientList', path: '',
    operationId: 59, operationCode: 'OPS59', operationName: 'View Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  {
    isActive: true,
    key: 'clients', routeName: 'ClientDetails', path: 'details',
    operationId: 59, operationCode: 'OPS59', operationName: 'View Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  {
    isActive: true,
    key: 'clients', routeName: 'CreateClient', path: 'create',
    operationId: 60, operationCode: 'OPS60', operationName: 'Create Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  {
    isActive: true,
    key: 'clients', routeName: 'UpdateClient', path: 'edit',
    operationId: 60, operationCode: 'OPS60', operationName: 'Edit Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  {
    isActive: true,
    key: 'clients', routeName: 'EditClient', path: 'edit/:id',
    operationId: 60, operationCode: 'OPS60', operationName: 'Edit Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  {
    isActive: true,
    key: 'clients', routeName: 'HistoryClient', path: 'history/:id',
    operationId: 60, operationCode: 'OPS60', operationName: 'History Client',
    resourceId: 13, resourceCode: 'R013', resourceName: 'Client',
    moduleId: 5, moduleCode: 'M005', moduleName: 'Client',
  },
  
{
  isActive: true,  
  key: 'clients', routeName: 'QuotationList', path: 'quotationlist',  
  operationId: 59, operationCode: 'OPS59', operationName: 'View Client',  
  resourceId: 13, resourceCode: 'R013', resourceName:'Client',  
  moduleId: 5, moduleCode: 'M005', moduleName: 'Client',  
  },
  //MFE Order
  {
    isActive: true,
    key: 'order', routeName: 'OrderList', path: '',
    operationId: 55, operationCode: 'OPS55', operationName: 'View Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  {
    isActive: true,
    key: 'order', routeName: 'CreateOrder', path: 'create',
    operationId: 56, operationCode: 'OPS56', operationName: 'Create Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  {
    isActive: true,
    key: 'order', routeName: 'OrderDetails', path: ':id',
    operationId: 55, operationCode: 'OPS55', operationName: 'View Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  {
    isActive: true,
    key: 'order', routeName: 'SelectProduct', path: 'select-product/:id',
    operationId: 56, operationCode: 'OPS56', operationName: 'Create Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  {
    isActive: true,
    key: 'order', routeName: 'SignOrder', path: 'sign',
    operationId: 57, operationCode: 'OPS57', operationName: 'Sign Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  {
    isActive: true,
    key: 'order', routeName: 'ApproveOrder', path: 'approve',
    operationId: 58, operationCode: 'OPS58', operationName: 'Approve Order',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M004', moduleName: 'Order',
  },
  // MFE Voucher
  {
    isActive: true,
    key: 'voucher', routeName: 'VoucherList', path: 'voucher-list',
    operationId: 73, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 15, resourceCode: 'R015', resourceName: 'Voucher',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'voucher', routeName: 'VoucherDetails', path: 'voucher-details/:id',
    operationId: 73, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 15, resourceCode: 'R015', resourceName: 'Voucher',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'voucher', routeName: 'VoucherHistory', path: 'voucher-history/:id',
    operationId: 73, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 15, resourceCode: 'R015', resourceName: 'Voucher',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'voucher', routeName: 'InventoryList', path: 'inventory/overview',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'voucher', routeName: 'InventoryDetails', path: 'inventory/sku-details/:id',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'voucher', routeName: 'InventoryBatchDetails', path: 'inventory/inventory-batch-details/:id',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  // MFE Batch Processor
  // TODO: change id and code to 77 when the operation will be added
  // currently OPS77 don't exist yet, waiting for Fight Club team to finish US38830
  {
    isActive: true,
    key: 'batch-processor', routeName: 'InventoryBatchDetails', path: 'voucher/inventory-list',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'batch-processor', routeName: 'InventoryBatchDetails', path: 'voucher/voucher-operations-list',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'batch-processor', routeName: 'InventoryBatchDetails', path: 'voucher/inventory-list/:id',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'batch-processor', routeName: 'InventoryBatchDetails', path: 'voucher/voucher-operations-list/:id',
    operationId: 76, operationCode: 'OPS76', operationName: 'View Inventory',
    resourceId: 16, resourceCode: 'R016', resourceName: 'Inventory',
    moduleId: 6, moduleCode: 'M006', moduleName: 'Voucher',
  },
  {
    isActive: true,
    key: 'batch-processor', routeName: 'BatchOrderList', path: 'order/batch-order-list',
    operationId: 76, operationCode: 'OPS76', operationName: 'Batch Order List',
    resourceId: 12, resourceCode: 'R012', resourceName: 'Order',
    moduleId: 4, moduleCode: 'M006', moduleName: 'Order',
  },
  // MFE System
  {
    isActive: true,
    key: 'system', routeName: 'MediaLibrary', path: 'media-library',
    operationId: 78, operationCode: 'OPS78', operationName: 'Media Library',
    resourceId: 17, resourceCode: 'R017', resourceName: 'Media Library',
    moduleId: 7, moduleCode: 'M007', moduleName: 'System',
  },
  {
    isActive: true,
    key: 'system', routeName: 'TemplateList', path: 'template-list',
    operationId: 80, operationCode: 'OPS80', operationName: 'Template List',
    resourceId: 18, resourceCode: 'R018', resourceName: 'Template List',
    moduleId: 7, moduleCode: 'M007', moduleName: 'System',
  },
  {
    isActive: true,
    key: 'system', routeName: 'AddTemplate', path: 'template-list/create',
    operationId: 81, operationCode: 'OPS81', operationName: 'Create Template',
    resourceId: 18, resourceCode: 'R018', resourceName: 'Template List',
    moduleId: 7, moduleCode: 'M007', moduleName: 'System',
  },
  {
    isActive: true,
    key: 'system', routeName: 'EditTemplate', path: 'template-list/edit/:id',
    operationId: 81, operationCode: 'OPS81', operationName: 'Edit Template',
    resourceId: 18, resourceCode: 'R018', resourceName: 'Template List',
    moduleId: 7, moduleCode: 'M007', moduleName: 'System',
  },
];
