export const environment = {
  local:false,
  production: false,
  demo: 'saas', // other possible options are creative and modern
  GOOGLE_MAPS_API_KEY: 'AIzaSyDpgQMpcfx1QU-8SM-ljcgjG4xrYtIYby4',
  apiUrl: "api-dev.txc.edenred.net/gateway/",
  connectorApiUrl: "api-dev.txc.edenred.net/connector/",
  landingUrl: "https://esg-txcloud-new-reverseproxy-dev-asse-web-d.azurewebsites.net",
  applyTemplateFeature: true,
  add_role_op_id : 1,
  upd_role_op_id : 2,
  view_role_op_id : 3,
  add_admin_op_id : 4,
  upd_admin_op_id : 5,
  view_admin_op_id : 6,
  add_user_op_id  : 7,
  upd_user_op_id : 8,
  view_user_op_id : 9,
  add_bu_mngr_op_id : 10,
  upd_bu_mngr_op_id : 11,
  view_bu_mngr_op_id : 12,
  add_tenant_op_id : 13,
  upd_tenant_op_id : 14,
  view_tenant_op_id : 15,
  role_mngmt_res_id : 1,
  admin_mngmt_res_id : 2,
  user_mngmt_res_id : 3,
  tenant_mngmt_res_id : 4,
  merchant_mngmt_res_id : 5,
  product_mngmt_res_id : 6,
  product_view_op_id: 23,
  product_create_op_id: 24,
  product_approve_op_id: 26
};
